// data.js
window.LECTURES = [
  {
    id: 1,
    title: "Intro to Wine",
    subtitle: "Weather, process, etc.",
    notesPath: "notes/lecture1.html",
    wines: [
      { name: "Chablis \"Terroir de Chichée\", Piuze", image: "images/lecture1/wine1.png", rating: "4.0/10" },
      { name: "Rombauer Chardonnay", image: "images/lecture1/wine2.png", rating: "5.0/10" },
      { name: "Schieferkristall Riesling Trocken, Karthäuserhof - 2021", image: "images/lecture1/wine3.png", rating: "3.5/10" },
      { name: "Harmand Geoffroy \"La Nouroy\"", image: "images/lecture1/wine4.png", rating: "5.0/10" },
      { name: "Bench Pinot Noir, Sonoma Coast - 2023", image: "images/lecture1/wine5.png", rating: "5.0/10" },
    ],
  },
  {
    id: 2,
    title: "Sparkling Wine",
    subtitle: "Loire / Burgundy styles",
    notesPath: "notes/lecture2.html",
    wines: [
      { name: "Mouzon-Leroux \"L'atavique Tradition\"", image: "images/lecture2/wine1.png", rating: "4.0/10" },
      { name: "Lahèrte Frères, \"Rosé de Meunier\", Extra Brut - NV", image: "images/lecture2/wine2.png", rating: "5.0/10" },
      { name: "Prosecco Superiore \"Primario\" Extra Dry, Ruge - NV", image: "images/lecture2/wine3.png", rating: "5.0/10" },
      { name: "Franciacorta Brut \"Cuvée Prestige\", Ca' del Bosco - NV", image: "images/lecture2/wine4.png", rating: "5.0/10" },
      { name: "Juve y Camps Brut Nature, Reserva de la Familia - 2021", image: "images/lecture2/wine5.png", rating: "4.0/10" },
      { name: "Moscato d'asti \"La Rosa Selvatica\", Icardi - 2024", image: "images/lecture2/wine6.png", rating: "7.0/10" },
    ],
  },
  {
    id: 3,
    title: "Northern France",
    subtitle: "Cabernet Sauvignon, Pinot Noir",
    notesPath: "notes/lecture3.html",
    wines: [
      { name: "Riesling Grand Cru \"Frankstein\", Manbach - 2022", image: "images/lecture3/wine1.png", rating: "3.0/10" },
      { name: "Touraine Sauvignon Blanc \"Clos de la Grange,\" - 2024", image: "images/lecture3/wine2.png", rating: "3.5/10" },
      { name: "Chinon \"Les Picasses\", Olga Raffault - 2020", image: "images/lecture3/wine3.png", rating: "4.0/10" },
      { name: "Bourgogne Blanc \"Le Clos du Chateau\"", image: "images/lecture3/wine4.png", rating: "7.0/10" },
      { name: "Marcel Lapierre, Raisins Gaulois 2024", image: "images/lecture3/wine5.png", rating: "4.0/10" },
      { name: "\"Les Nouroys\", Harmand-Geoffroy - 2021", image: "images/lecture3/wine6.png", rating: "5.0/10" },
    ],
  },
  {
    id: 4,
    title: "Southern France",
    subtitle: "Loire / Burgundy styles",
    notesPath: "notes/lecture4.html",
    wines: [
      { name: "Ch. Guiraud “Le G de Château Guiraud” - 2022", image: "images/lecture4/wine1.png", rating: "9.0/10" },
      { name: "Chateau Cantemerle Haut-Medoc 2022", image: "images/lecture4/wine2.png", rating: "7.5/10" },
      { name: "St. Joseph \"Rue des Poissoniers\", Julien Pilon - 2022", image: "images/lecture4/wine3.png", rating: "7.5/10" },
      { name: "Côtes-du-Rhône \"Mon Coeur\", Chave - 2023", image: "images/lecture4/wine4.png", rating: "9.5/10" },
      { name: "Whispering Angel Rose", image: "images/lecture4/wine5.png", rating: "9.0/10" },
      { name: "Fond Cypres “Premier Jus” 2024", image: "images/lecture4/wine6.png", rating: "5.0/10" },
    ],
  },
  {
    id: 5,
    title: "Spain and Portugal",
    subtitle: "Tempranillo, Touriga Nacional",
    notesPath: "notes/lecture5.html",
    wines: [
      { name: "Vinho Verde, Broadbent - NV", image: "images/lecture5/wine1.png", rating: "6.0/10" },
      { name: "Albariño \"Dandelion\" Alberto Nanclares - 2023", image: "images/lecture5/wine2.png", rating: "2.0/10" },
      { name: "Ribeira Sacra Mencía \"Vel’uveyra\", Ronsel do Sil - 2019", image: "images/lecture5/wine3.png", rating: "2.0/10" },
      { name: "Quinto de Lemos \"Dona Santana\" Dão - 2008", image: "images/lecture5/wine4.png", rating: "3.0/10" },
      { name: "Viña Cubillo Rioja Lopez de Heredia - 2017", image: "images/lecture5/wine5.png", rating: "6.5/10" },
      { name: "Prioriat \"Bellmunt\" Mas d'en Gil - 2021", image: "images/lecture5/wine6.png", rating: "7.5/10" },
    ],
  },
  {
    id: 6,
    title: "Italy",
    subtitle: "Regional Diversity and DOC System",
    notesPath: "notes/lecture6.html",
    wines: [
      { name: "Barale Barolo 2020", image: "images/lecture6/wine1.png", rating: "9.0/10" },
      { name: "Le Bignete Valpolicella Ripasso", image: "images/lecture6/wine2.png", rating: "9.0/10" },
      { name: "Pinot Grigio, Borghi Ad Est - 2024", image: "images/lecture6/wine3.png", rating: "8.5/10" },
      { name: "Montesecondo Chianti Classico", image: "images/lecture6/wine4.png", rating: "8.0/10" },
      { name: "Brunello di Montalcino - 2020", image: "images/lecture6/wine5.png", rating: "7.0/10" },
      { name: "Fiano di Avellino \"Iclassici\", Torricino - 2024", image: "images/lecture6/wine6.png", rating: "6.0/10" },
      { name: "Azienda Agricola Kalma “Lifasi”", image: "images/lecture6/wine7.png", rating: "2.5/10" },
    ],
  },
  
];